name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Release
        run: |
          npx semantic-release@21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
