name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # prevent semantic-release from making changes by "github-actions" user as it doesn't trigger other workflows
          # source: https://github.com/semantic-release/semantic-release/blob/8fda7fd423d24e7b425fbee83790f49dd0478e2d/docs/recipes/ci-configurations/github-actions.md#pushing-packagejson-changes-to-a-master-branch
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v22.8.0
      - name: Set up semantic-release
        run: |
          npx semantic-release@24.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
